import React from "react";

const metadata = {
    description: "Generated by Next.js",
    title: "Next.js",
};

/**
 * The root layout of the application
 *
 * @param param0
 * @returns
 */
const RootLayout = ({
    children,
}: {
    children: React.ReactNode;
}): JSX.Element => (
    <html lang="en">
        <head>
            <link
                crossOrigin="anonymous"
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
                integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
                rel="stylesheet"
            />
        </head>
        <body>{children}</body>
    </html>
);

export { RootLayout as default, metadata };
